[package]
name = "send_it"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.4"
reqwest = { version = "0.11.22", features = ["json"] }
json = "0.12.4"
